services:
  - type: web
    name: go-backend
    runtime: go
    plan: free
    region: oregon
    branch: main
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DB_URL
        sync: false
